[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

# 🛡️ 架构师沙箱设计：局部项目环境变量隔离（relative = true 会自动将相对路径转化为绝对物理路径）
[env]
ORT_LIB_PATH = { value = "lib_dylib", relative = true }
ORT_PREFER_DYNAMIC_LINK = "1"

# 🧭 【核心自愈】告诉 Linux 运行时装载器（ld.so），去我们的局部沙箱目录下寻找 .so 动态链接库
LD_LIBRARY_PATH = { value = "lib_dylib", relative = true }

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-args=-Wl,-rpath,$ORIGIN/../../lib_dylib"
]